package com.springboot.springbootproject.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.user_Type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.weicar
     *
     * @mbggenerated
     */
    private String weicar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.QQ
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.login_Date
     *
     * @mbggenerated
     */
    private Date loginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.phoneCode
     *
     * @mbggenerated
     */
    private String phonecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.rigDateTime
     *
     * @mbggenerated
     */
    private Date rigdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.passWord
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.login_Name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.user_Name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuwu_user.lock_type
     *
     * @mbggenerated
     */
    private Integer lockType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.id
     *
     * @return the value of wuwu_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.id
     *
     * @param id the value for wuwu_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.user_Type
     *
     * @return the value of wuwu_user.user_Type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.user_Type
     *
     * @param userType the value for wuwu_user.user_Type
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.weicar
     *
     * @return the value of wuwu_user.weicar
     *
     * @mbggenerated
     */
    public String getWeicar() {
        return weicar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.weicar
     *
     * @param weicar the value for wuwu_user.weicar
     *
     * @mbggenerated
     */
    public void setWeicar(String weicar) {
        this.weicar = weicar == null ? null : weicar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.QQ
     *
     * @return the value of wuwu_user.QQ
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.QQ
     *
     * @param qq the value for wuwu_user.QQ
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.login_Date
     *
     * @return the value of wuwu_user.login_Date
     *
     * @mbggenerated
     */
    public Date getLoginDate() {
        return loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.login_Date
     *
     * @param loginDate the value for wuwu_user.login_Date
     *
     * @mbggenerated
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.phoneCode
     *
     * @return the value of wuwu_user.phoneCode
     *
     * @mbggenerated
     */
    public String getPhonecode() {
        return phonecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.phoneCode
     *
     * @param phonecode the value for wuwu_user.phoneCode
     *
     * @mbggenerated
     */
    public void setPhonecode(String phonecode) {
        this.phonecode = phonecode == null ? null : phonecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.rigDateTime
     *
     * @return the value of wuwu_user.rigDateTime
     *
     * @mbggenerated
     */
    public Date getRigdatetime() {
        return rigdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.rigDateTime
     *
     * @param rigdatetime the value for wuwu_user.rigDateTime
     *
     * @mbggenerated
     */
    public void setRigdatetime(Date rigdatetime) {
        this.rigdatetime = rigdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.remark
     *
     * @return the value of wuwu_user.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.remark
     *
     * @param remark the value for wuwu_user.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.passWord
     *
     * @return the value of wuwu_user.passWord
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.passWord
     *
     * @param password the value for wuwu_user.passWord
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.login_Name
     *
     * @return the value of wuwu_user.login_Name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.login_Name
     *
     * @param loginName the value for wuwu_user.login_Name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.user_Name
     *
     * @return the value of wuwu_user.user_Name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.user_Name
     *
     * @param userName the value for wuwu_user.user_Name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuwu_user.lock_type
     *
     * @return the value of wuwu_user.lock_type
     *
     * @mbggenerated
     */
    public Integer getLockType() {
        return lockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuwu_user.lock_type
     *
     * @param lockType the value for wuwu_user.lock_type
     *
     * @mbggenerated
     */
    public void setLockType(Integer lockType) {
        this.lockType = lockType;
    }
}